# Generated by Django 4.1.6 on 2023-02-05 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('isbn', models.IntegerField(max_length=20, unique=True)),
                ('publisher', models.CharField(max_length=200)),
                ('page', models.IntegerField(max_length=5)),
                ('is_borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('debt', models.PositiveSmallIntegerField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2023, 2, 12, 16, 37, 36, 408237))),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('return_status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.members')),
            ],
        ),
    ]
