# Generated by Django 4.1.6 on 2023-02-05 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='debt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 16, 39, 21, 312782)),
        ),
    ]
