# Generated by Django 4.1.6 on 2023-02-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_books_isbn_alter_books_page_alter_members_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 23, 33, 35, 213849)),
        ),
    ]
