# Generated by Django 4.1.6 on 2023-02-06 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transactions_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 17, 50, 471236)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 17, 50, 471236)),
        ),
    ]
